spring:
  cloud:
    config:
      initialize-on-context-refresh: true
    gateway:
      routes:
        - id: first
          uri: http://localhost:9000
          predicates:
            - Path=/first/**
          filters:
            - RewritePath=/first/?(?<segment>.*), /$\{segment}

        - id: second
          uri: http://localhost:9001
          predicates:
            - Path=/second/**
          filters:
            - RewritePath=/second/?(?<segment>.*),/$\{segment}
        - id: third1
          uri: http://localhost:9002
          predicates:
            - Path=/third/**
          filters:
            - RewritePath=/third/?(?<segment>.*),/$\{segment}
  jpa:
    open-in-view: false

# Данная проперти отвечает за перезагрузку контекста
context:
  reload:
    #отвечает за включение перезагрузки контекста
    enable: true
    #крон выражение запуска по расписанию
    cron: 0/10 * * * * *
    #  пересоздание бинов после перезагрузки контекста (нужно в данный момент для корректного отображения сваггера)
    force-recreate: true


springdoc:
  cache:
    disabled: true
  # We should display api-gateway as well
  swagger-ui:
    urls[0]:
      name: api-gateway
      url: /v3/api-docs
  group-configs[0]:
    group: api-gateway
    pathsToMatch: /**
  # Набор кастомных параметров  для свагерра
  custom:
    # список приложений для которых не нужен свагер
    without-swagger:
      - none
    # список приложений для которых надо 2 версию свагерра подтягитивать
    swagger-v2:
      - none
