spring:
  cloud:
    config:
      initialize-on-context-refresh: true
    gateway:
      routes:
        - id: first
          uri: http://localhost:9000
          predicates:
            - Path=/first/**
          filters:
            - RewritePath=/first/?(?<segment>.*), /$\{segment}

        - id: second
          uri: http://localhost:9001
          predicates:
            - Path=/second/**
          filters:
            - RewritePath=/second/?(?<segment>.*),/$\{segment}
        - id:  NEW 1
          uri: http://localhost:9002
          predicates:
            - Path=/third/**
          filters:
            - RewritePath=/third/?(?<segment>.*),/$\{segment}
        - id:  NEW 3
          uri: http://localhost:9002
          predicates:
            - Path=/new3/**
          filters:
            - RewritePath=/new2/?(?<segment>.*),/$\{segment}
        - id: NEW 4
          uri: http://localhost:9002
          predicates:
            - Path=/new4/**
          filters:
            - RewritePath=/new4/?(?<segment>.*),/$\{segment}
        - id: NEW 5
          uri: http://localhost:9002
          predicates:
            - Path=/new4/**
          filters:
            - RewritePath=/new4/?(?<segment>.*),/$\{segment}
  jpa:
    open-in-view: false


logging:
  level:
    org.springframework.cloud.gateway: DEBUG

management:
  endpoint:
    prometheus.enabled: false
    metrics.enabled: true
  endpoints:
    web:
      exposure.include: [ 'prometheus', 'health', 'health-soft', 'configprops', 'env', 'mappings', 'refresh','routes' ]
  metrics.export.prometheus.enabled: true


springdoc:
  cache:
    disabled: true
  # We should display api-gateway as well
  swagger-ui:
    urls[0]:
      name: api-gateway
      url: /v3/api-docs

