spring:
  cloud:
    config:
      initialize-on-context-refresh: true
    gateway:
      routes:
        - id: first
          uri: http://localhost:9000
          predicates:
            - Path=/first/**
          filters:
            - RewritePath=/first/?(?<segment>.*), /$\{segment}
        - id: second
          uri: http://localhost:9001
          predicates:
            - Path=/second/**
          filters:
            - RewritePath=/second/?(?<segment>.*),/$\{segment}

        - id: third 1
          uri: http://localhost:9002
          predicates:
            - Path=/third/**
          filters:
            - RewritePath=/third/?(?<segment>.*),/$\{segment}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
  jpa:
    open-in-view: false

# Данная проперти отвечает за перезагрузку контекста
context:
  reload:
    #отвечает за включение перезагрузки контекста
    enable: true
    #крон выражение запуска по расписанию
    cron: 0/10 * * * * *
    #  пересоздание бинов после перезагрузки контекста (нужно в данный момент для корректного отображения сваггера)
    force-recreate: true


springdoc:
  cache:
    disabled: true
  # We should display api-gateway as well
  swagger-ui:
    urls:
      - name: api-gateway
        url: /v3/api-docs
      - name: first
        url: /v3/api-docs/first
      - name: second
        url: /v3/api-docs/second
      - name: third
        url: /v3/api-docs/third
  # Набор кастомных параметров  для свагерра
  custom:
    # список приложений для которых не нужен свагер
    without-swagger:
      - none
    # список приложений для которых надо 2 версию свагерра подтягитивать
    swagger-v2:
      - none

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
#  level:
#    org.springframework.cloud.gateway: TRACE
#    org.springframework.http.server.reactive: TRACE
